Three state button
EkaterinaPoddubskaya/modules pull request #1
Opened 2024-08-27 14:35 UTC by EkaterinaPoddubskaya

Created three-state button via webix.protoUI
Enabled sorting/unsorting of film list by clicking that button

2024-08-27 15:19 UTC, VeraOrekhXB requested changes

2024-08-27 15:19 UTC, VeraOrekhXB commented on scripts/main.js
> +        this.attachEvent("onItemClick", () => {
The event has to be detached on `onDestruct` event

2024-08-27 15:19 UTC, VeraOrekhXB commented on scripts/main.js
> +            webix.html.removeCss(this.getNode(), BUTTON_STATE[button_state_index].style);
You may add a method, for example, `changeState`
It makes it easier & quicker to understand what is going on + it's reusable and could be called on another even handler too

2024-08-27 15:19 UTC, VeraOrekhXB commented on scripts/main.js
> +                    $$("filmList").sort("#title#", "asc");
It's better to put `$$("filmList")` value into variable

2024-08-27 15:19 UTC, VeraOrekhXB commented on scripts/main.js
> +            webix.html.addCss(this.getNode(), BUTTON_STATE[button_state_index].style);
`this.getNode()` put into variable

2024-08-28 11:11 UTC, EkaterinaPoddubskaya commented
I din't put config.state into a variable in changeState function because it's value changes throughout the function and I'll have to reasign it twice

2024-08-28 12:24 UTC, VeraOrekhXB requested changes

2024-08-28 12:24 UTC, VeraOrekhXB commented on scripts/threeStateButton.js
> +            config.state = this.config.state;
What is the purpose of the string?

2024-08-28 16:35 UTC, VeraOrekhXB approved these changes

2024-08-28 16:52 UTC, merged